name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: RidaHajjAli
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: output/
          message: "chore: update pacman contribution graph"
