name: Update README

on:
  schedule:
    # Runs every hour at the top of the hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  # This permission is essential for the action to be able to push code
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code.
      # The git-auto-commit-action needs access to the repo.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Modify the README file
      # This step remains the same. We make our desired change to the file.
      - name: Update timestamp in README
        run: |
          # This command finds a placeholder and replaces it with the current timestamp.
          # Make sure you have a line like "Last updated: <!-- LAST_UPDATED -->" in your README.md
          sed -i "s/<!-- LAST_UPDATED -->/$(date)/g" README.md

      # Step 3: Commit and push the changes using a dedicated action
      # Instead of manual git commands which can be brittle, this action is purpose-built
      # for committing changes from within a workflow. It handles checking for changes,
      # configuring git, committing, and pushing automatically.
      - name: Commit and push updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Auto-update README with latest timestamp"
          # This specifies which file(s) to check for changes.
          file_pattern: README.md
          # Pushes directly to the main branch.
          branch: main

