name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace token in README
        run: |
          sed -i "s/TOKEN_PLACEHOLDER/${{ secrets.GH_TOKEN }}/g" README.md

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
